# -*- coding: utf-8 -*-
"""Untitled74.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rXC3yQ34UrGPDBox1pIrJMkOeNj9H_Zn
"""

import matplotlib.pyplot as plt
import numpy as np
x=np.array([0,8])
y=np.array([0,350])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
x=np.array([1,2,4,6])
y=np.array([3,8,9,10])
plt.plot(x,y)
plt.show()

import matplotlib.pyplot as plt
import numpy as np
y=np.array([3,8,1,10])
plt.plot(y, marker='D')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 1. x qiymatlari oraliqini yaratish
x = np.linspace(-10, 10, 400)  # -10 dan 10 gacha 400 ta nuqta

# 2. Parabola tenglamasi: y = ax^2 + bx + c (a = 1, b = 0, c = 0)
a = int(input("a = "))
b = int(input("b = "))
c = int(input("c = "))
y = a * x**2 + b * x + c  # y = x^2

# 3. Parabolani chizish
plt.figure(figsize=(8, 6))
plt.plot(x, y, label='y = x^2', color='blue')
plt.title('Parabola chizish')
plt.xlabel('x')
plt.ylabel('y')
plt.axhline(0, color='black',linewidth=0.5, ls='--')  # x o'qini ko'rsatish
plt.axvline(0, color='black',linewidth=0.5, ls='--')  # y o'qini ko'rsatish
plt.grid(color = 'gray', linestyle = '--', linewidth = 0.5)  # Tarmoq chizish
plt.legend()
plt.show()